### ISSUE TITLE
Eurostat - missing codelists values

### ISSUE THREAD

**Issue by zymon** [khaeru/sdmx#116]
`import sdmx`

`client=sdmx.Client('ESTAT')`
`flow=client.dataflow('GOV_10Q_GGNFA', params={'detail': 'referencepartial'})`
`# take the first dataflow from the list (anyway there's only one)`
`df=next(iter(flow.dataflow.items()))[1]`

`# check codelists`
`df.codelist`

Result:
{'ESTAT:GEO': <Codelist ESTAT:GEO(13.1) (0 items)>, 'S_ADJ': <Codelist ESTAT:S_ADJ(1.9) (4 items): Seasonal adjustment>, 'ESTAT:UNIT': <Codelist ESTAT:UNIT(15.2) (0 items)>, 'SECTOR': <Codelist ESTAT:SECTOR(9.2) (6 items): Sector>, 'ESTAT:FREQ': <Codelist ESTAT:FREQ(1.31) (0 items)>, 'ESTAT:OBS_FLAG': <Codelist ESTAT:OBS_FLAG(1.31) (0 items)>, 'ESTAT:NA_ITEM': <Codelist ESTAT:NA_ITEM(9.0) (0 items)>}

GEO: has no items, the same for UNIT

Other way to get the codelists also doesn't work. Let's try with GEO:
`df.structure.dimensions.components[5].local_representation`

Which gives:
<Representation: GEO, []>

**Comment by khaeru** [comment]
Thanks for the clear report, I was able to reproduce this easily.

**Comment by zymon** [comment]
Hello,
I tried with version 2.8.0 and still can't get the valid codelist.

`import sdmx`
`client=sdmx.Client('ESTAT')`
`msg=client.dataflow('GOV_10Q_GGNFA', params={'detail': 'referencepartial'})`
`msg.codelist`


output:
{'ESTAT:GEO': <Codelist ESTAT:GEO(13.1) (0 items)>, 'S_ADJ': <Codelist ESTAT:S_ADJ(1.9) (4 items): Seasonal adjustment>, 'ESTAT:UNIT': <Codelist ESTAT:UNIT(15.2) (0 items)>, 'SECTOR': <Codelist ESTAT:SECTOR(9.2) (6 items): Sector>, 'ESTAT:FREQ': <Codelist ESTAT:FREQ(1.31) (0 items)>, 'ESTAT:OBS_FLAG': <Codelist ESTAT:OBS_FLAG(1.31) (0 items)>, 'ESTAT:NA_ITEM': <Codelist ESTAT:NA_ITEM(9.0) (0 items)>}

The same happens when the "referencepartial" is not used:

`msg=client.dataflow('GOV_10Q_GGNFA')`

INFO:sdmx.client:Request https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/dataflow/ESTAT/GOV_10Q_GGNFA/latest?references=descendants
INFO:sdmx.client:with headers {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
DEBUG:requests_cache.policy.actions:Cache directives from request headers: {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ec.europa.eu:443
DEBUG:urllib3.connectionpool:https://ec.europa.eu:443 "GET /eurostat/api/dissemination/sdmx/2.1/dataflow/ESTAT/GOV_10Q_GGNFA/latest?references=descendants HTTP/1.1" 200 None
DEBUG:requests_cache.session:Pre-cache checks for response from https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/dataflow/ESTAT/GOV_10Q_GGNFA/latest?references=descendants: {'disabled cache': False, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}

`msg.codelist`

output:
{'SECTOR': <Codelist ESTAT:SECTOR(9.2) (68 items): Sector>, 'ESTAT:OBS_FLAG': <Codelist ESTAT:OBS_FLAG(1.31) (0 items)>, 'ESTAT:FREQ': <Codelist ESTAT:FREQ(1.31) (0 items)>, 'S_ADJ': <Codelist ESTAT:S_ADJ(1.9) (6 items): Seasonal adjustment>, 'ESTAT:UNIT': <Codelist ESTAT:UNIT(15.2) (0 items)>, 'ESTAT:GEO': <Codelist ESTAT:GEO(13.1) (0 items)>, 'ESTAT:NA_ITEM': <Codelist ESTAT:NA_ITEM(9.0) (0 items)>}

As you can see GEO and even FREQ are empty.

**Comment by khaeru** [comment]
Yes, that's expected. The PR is merged and the issue is fixed, but there is not yet a release with those changes. v2.8.0 does not contain them.

You can check that by:
- Noticing at https://github.com/khaeru/sdmx/releases that v2.8.0 was released 2023-03-31, whereas the PR was merged later, on 2023-04-03.
- At https://github.com/khaeru/sdmx/releases/tag/v2.8.0, clicking the link "15 commits to main since this release", and seeing that the fix is among those unreleased changes.

You can use `pip` to install from any branch at any time (https://pip.pypa.io/en/stable/topics/vcs-support/): `pip install "sdmx1 @ git+https://github.com/khaeru/sdmx.git@gmain"`
