### ISSUE TITLE
Estat with DSD: XMLParseError on 2nd resource

### ISSUE THREAD

**Issue by mephinet** [khaeru/sdmx#199]
When requesting 2 different Eurostat resources, an sdmx.exceptions.XMLParseError is thrown. However, when requesting only one of those resources, no matter which one, thinks work as expected.

I'm rather clueless here, so I've created a minimal reproducer: https://gist.github.com/mephinet/e5ef7f448661587f6de676e05aef0a48

```sh
python estat-reproducer.py 1  # requests NAMQ_10_GDP with DSD
python estat-reproducer.py 2  # requests NAMA_10_GDP with DSD
python estat-reproducer.py 3  # requests both with DSD
python estat-reproducer.py 4  # requests both without DSD

```

The first two invocations, which only request 1 resource, return a correct dataframe. Invocation 3 requests both resources - and in this case an exception is thrown:

```
Traceback (most recent call last):
  File "/home/gortan/.pyenv/versions/finance-scrapers/lib/python3.12/site-packages/sdmx/reader/xml/common.py", line 197, in read_message
    raise NotImplementedError(element.tag, event) from None
NotImplementedError: ('{urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=ESTAT:NAMA_10_GDP(83.0):ObsLevelDim:TIME_PERIOD}DataSet', 'start')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gortan/repos/finance-scrapers/estat-reproducer.py", line 27, in <module>
    df2 = fetch(
          ^^^^^^
  File "/home/gortan/repos/finance-scrapers/estat-reproducer.py", line 12, in fetch
    data = client.data(resource_id=resource_id, key=key, params=params, dsd=dsd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gortan/.pyenv/versions/finance-scrapers/lib/python3.12/site-packages/sdmx/client.py", line 496, in get
    msg = reader.read_message(response_content, structure=kwargs.get("dsd", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gortan/.pyenv/versions/finance-scrapers/lib/python3.12/site-packages/sdmx/reader/xml/__init__.py", line 45, in read_message
    import_module(f"sdmx.reader.xml.{version}")
  File "/home/gortan/.pyenv/versions/finance-scrapers/lib/python3.12/site-packages/sdmx/reader/xml/common.py", line 218, in read_message
    raise XMLParseError from exc
sdmx.exceptions.XMLParseError: NotImplementedError: ('{urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=ESTAT:NAMA_10_GDP(83.0):ObsLevelDim:TIME_PERIOD}DataSet', 'start')
```

The forth invocation does not use a DSD, and works fine again.

I'm using sdmx1 version 2.18.0 with Python 3.12.4 on Arch Linux. I've uninstalled requests_cache, but that didn't change thing.
My uneducated guess is that the DSDs get mixed up during request processing..?

**Comment by khaeru** [comment]
Hi! Yes, I think you've run into a genuine bug here.

Briefly, there are two variants of “structure-specific” SDMX-ML visible in the wild. Sometimes we see things like this:
```xml
<mes:StructureSpecificData xmlns:mes="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message">
  <mes:DataSet>
    ...
  </mes:DataSet>
</mes:StructureSpecificData>
```
- Here the "standard" SDMX-ML namespace `"http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message"` with the prefix `mes:` is used for the \<mes:DataSet\> tag.

On the other hand, we sometimes see this:
```xml
<mes:StructureSpecificData
  xmlns:mes="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message"
  xmlns:u="urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=ESTAT:NAMA_10_GDP(32.1):ObsLevelDim:TIME_PERIOD">
  <u:DataSet>
    ...
  </u:DataSet>
</mes:StructureSpecificData>
```
- Here, a namespace name is defined with the SDMX URN `"urn:sdmx:org.sdmx.infomodel…"` and the prefix `u:`, and then a **different XML tag** is used: \<u:DataSet\>.

The first example is generic, but the second example is particular to the specific data structure of the message being read. In other words, the prefix `u:` could be associated with a different URN in each message.

So we have this code that is supposed to register handlers to look for the \<u:DataSet\> tag with the `u:` namespace name appearing in *that particular message*: https://github.com/khaeru/sdmx/blob/9186c89e62148a9c7bb206e3a6df2308282bb947/sdmx/reader/xml/v21.py#L154-L161

I think I've written this in a clumsy way, and so in your use-case the handlers are not added. This then leads to the NotImplementedError when the reader hits <u:DataSet> and doesn't know what to do with it.

Thank you for providing code to reproduce; I will use this to make and test a fix.

As for a workaround, I am not sure but you might try something like:
```python
from sdmx.format.xml import v21

print(v21.FORMAT.NS)
```
…before, between, and after your various read events; maybe you could `.pop()` something off this collection to prevent the error.

**Comment by mephinet** [comment]
Thanks for confirmation and explanation!

Side note: I am always confused by the log line 
> Use supplied structure=… argument for non–structure-specific message"

 Is this an informational message like "this library is now using...", or is it a complaint ("stupid developer, it does not make any sense using..."), or is it a suggestion ("it would be more efficient if you supplied...")? I fail to figure that out. Maybe you could improve this message while you're at that particular chunk of code to make the intention clearer.
Thanks a lot, by the way, for the awesome work & support!

**Comment by khaeru** [comment]
> Side note: I am always confused by the log line
> 
> > Use supplied structure=… argument for non–structure-specific message"
> 
> Is this an informational message like "this library is now using...", or is it a complaint ("stupid developer, it does not make any sense using..."), or is it a suggestion ("it would be more efficient if you supplied...")? I fail to figure that out. Maybe you could improve this message while you're at that particular chunk of code to make the intention clearer.

That was being displayed because I had accidentally left a `log.setLevel(logging.DEBUG)` (meant, obviously, for debugging) in .reader.xml.v21. The last commit on #200 removes it.

About the intention: this package basically will infer a data structure definition (DSD) on-the-fly while reading an SDMX-ML message—but only under some circumstances; most easily for ‘generic’ (non-structure-specific) messages. For a structure-specific data message, the DSD has to come from somewhere. With the `structure=dsd` (or deprecated `dsd=dsd`) keyword argument, the user (as you've done) supplies one directly; but it's also imaginable that the code could, for instance, automatically make a query to obtain it (if identified by a URN), or other affordances. There's also no real check or guarantee that the user-supplied DSD is the ‘right’ one corresponding to the message. The logging was to help debug all this.

Overall:
- From SDMX 3.0, *only* structure-specific data messages are supported. So maybe the inference behaviour can eventually be discarded or at least deprioritized, and instead more effort for supports to have the ‘right’ DSD to go with a particular data message.
- I appreciate that there are many possible use-cases, and it always helps to have documentation (also warnings and log messages) that cover them all but are also succinct and unobtrusive.

So I'll definitely keep that feedback in mind, next time this code is touched.

> Thanks a lot, by the way, for the awesome work & support!

Very welcome!

**Comment by mephinet** [comment]
Tested with 2.19.1 - works like a charm. Thanks a lot for taking care so quickly!
