### ISSUE TITLE
Wrong base URL for ISTAT source

### ISSUE THREAD

**Issue by Vysybyl** [khaeru/sdmx#209]
Hi,

The `"url"` property of the `"ISTAT"` source in `sources.json` is wrong (outdated, I guess).

It should be replaced with 
```json
"url": "https://sdmx.istat.it/SDMXWS/rest",
```
Sorry if I don't create a fork + PR for this, but it should be an easy fix.

I've found the right link [here](https://developers.italia.it/it/api/istat-sdmx-rest.html)

Thanks a lot

**Comment by khaeru** [comment]
I'd noticed the scheduled nightly runs of the tests for this source had failed for a week or so, but hadn't yet had time to investigate. I guess the change was recent. Thanks very much for the pointer to the new URL and docs!

I'll make a PR in the next few days. In the meantime to work around, one can override the [Source.url](https://sdmx1.readthedocs.io/en/latest/sources.html#sdmx.source.Source.url) property:
```python
>>> import sdmx
>>> ISTAT = sdmx.Client("ISTAT")

# Show the current base url in sources.json
>>> ISTAT.source.url
'https://esploradati.istat.it/SDMXWS/rest'

# Override
>>> ISTAT.source.url = "https://sdmx.istat.it/SDMXWS/rest"

>>> ISTAT.dataflow("47_850")
<sdmx.StructureMessage>
  <Header>
    id: 'IDREF72'
    prepared: '2024-12-09T14:13:28.435395+01:00'
    receiver: <Agency Unknown>
    sender: <Agency Unknown>
    source:
    test: False
  response: <Response [200]>
  Categorisation (1): 47_850@IT1@15@ISTAT_DW@10@47
  CategoryScheme (1): ISTAT_DW
  Codelist (11): CL_BASE_YEAR CL_FLAG CL_FREQ CL_ITTER107 CL_OBS_CONF C...
  ConceptScheme (2): CROSS_DOMAIN VARIAB_ALL
  DataflowDefinition (1): 47_850
  DataStructureDefinition (1): DCIS_SERVSOCEDU1
```

**Comment by khaeru** [comment]
In reviewing old issues and PRs, I remembered that in #104 (from 2022) @miccoli linked to a specific announcement that identifies `sdmx.istat.it/…` as an **old** base URL, to be retired, and `esploradati.istat.it/…` as the **new** one.

So I'll close this issue—but please comment if you find any newer info to the contrary.

**Comment by Vysybyl** [comment]
Hi!

Thanks for the replies and the info. It is possible that the old URL still works and that the new one is randomly failing. I will keep it in mind and maybe put together a monkey-patch on my local installation.
I will post here any new information I might run into.

Cheers,
