### ISSUE TITLE
Write "time series" format

### ISSUE THREAD

**Issue by brockfanning** [khaeru/sdmx#39]
I have been trying out the SDMX-ML writer, and it is working wonderfully. However I need to produce "time series" SDMX. For example, instead of `Obs` elements, I would like to create `Series` elements. And instead of `ObsKey` elements, I would like to create `SeriesKey` elements.

Is this already possible using the library or would this be an enhancement?

**Comment by brockfanning** [comment]
In looking at [the code](https://github.com/khaeru/sdmx/blob/master/sdmx/writer/xml.py) I see that Series and SeriesKey are already possible, and it is likely a matter of how I put together the datasets. I've been using [this helpful document](https://sdmx1.readthedocs.io/en/latest/howto/create.html#populate-a-data-set-with-observations) and I'm wondering if that is the point where I can do a time series instead.

**Comment by khaeru** [comment]
> it is likely a matter of how I put together the datasets. I've been using [this helpful document](https://sdmx1.readthedocs.io/en/latest/howto/create.html#populate-a-data-set-with-observations) and I'm wondering if that is the point where I can do a time series instead.

That's correct! If you've studied the Information Model, and also if you have looked at a time series data set that has been *read* using `sdmx`, you can see how the [`DataSet.series`](https://sdmx1.readthedocs.io/en/latest/api.html#sdmx.model.DataSet.series) attribute stores the mapping between SeriesKey objects and the associated Observation objects within one DataSet.

So it sounds like you want to extend the example from the documentation to (a) create SeriesKey objects, (b) associate Observation objects with them within a DataSet, and then (c) run that through `writer.xml`.

This should be _possible_, but it is not yet officially supported, which means fully tested and documented. That is indeed a desired enhancement. Once you have working code that does this, plus an example of the desired SDMX-ML output, then please post them here and we can add them as a permanent test that this usage works.

**Comment by khaeru** [comment]
P.S. be sure to also look at the existing tests. This one is parametrized with several different XML specimens that can be both read *and* written (making a "round trip"). One of them may resemble the kind of message you want to create:
https://github.com/khaeru/sdmx/blob/30d8145022ce4837fa426055b1039ec8b9910895/sdmx/tests/writer/test_writer_xml.py#L78-L123

**Comment by brockfanning** [comment]
@khaeru Thanks very much. It is still in progress, but I've got some code that appears to be working! I'll go ahead and post now:

```
import sdmx

# The particular DSD I used here was downloaded from:
# https://registry.sdmx.org/ws/public/sdmxapi/rest/datastructure/IAEG-SDGs/SDG/latest/?format=sdmx-2.1&detail=full&references=children
msg = sdmx.read_sdmx('SDG_DSD.xml')
dsd = msg.structure[0]

# Data rows showing an attribute (UNIT_MEASURE) and dimension (REF_AREA).
rows = [
    {
        'TIME_PERIOD': '2008',
        'UNIT_MEASURE': 'P',
        'REF_AREA': '1',
        'OBS_VALUE': '100',
    },
    {
        'TIME_PERIOD': '2009',
        'UNIT_MEASURE': 'P',
        'REF_AREA': '1',
        'OBS_VALUE': '150',
    },
]

serieses = {}
for row in rows:
    # Make a series key from the dimension.
    series_key = dsd.make_key(sdmx.model.SeriesKey, {
        'REF_AREA': row['REF_AREA'],
    })
    # Make a dict with the attribute value.
    unit_measure = next(attr for attr in dsd.attributes if attr.id == 'UNIT_MEASURE')
    attributes = {
        'UNIT_MEASURE': sdmx.model.AttributeValue(value_for=unit_measure, value=row['UNIT_MEASURE'])
    }
    # Make another key for the ObsDimension element.
    dimension_key = dsd.make_key(sdmx.model.Key, values={
        'TIME_PERIOD': row['TIME_PERIOD'],
    })
    observation = sdmx.model.Observation(
        series_key=series_key,
        dimension=dimension_key,
        attached_attribute=attributes,
        # The primary measure in the DSD is "OBS_VALUE".
        value_for=dsd.measures[0],
        value=row[dsd.measures[0].id],
    )

    if series_key not in serieses:
         serieses[series_key] = []
    serieses[series_key].append(observation)

dataset = sdmx.model.GenericTimeSeriesDataSet(
    structured_by=dsd,
    series=serieses,
)
dfd = sdmx.model.DataflowDefinition(id="OPEN_SDG_DFD", structure=dsd)
msg = sdmx.message.DataMessage(data=[dataset], dataflow=dfd)
with open('example.xml', 'wb') as f:
    f.write(sdmx.to_xml(msg))
```

This code generates the following:

```
<mes:GenericData xmlns:com="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common"
    xmlns:data="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/structurespecific"
    xmlns:str="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure"
    xmlns:mes="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message"
    xmlns:gen="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/generic"
    xmlns:footer="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <mes:Header>
        <mes:Test>false</mes:Test>
        <mes:Structure structureID="SDG">
            <com:Structure>
                <URN>urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=IAEG-SDGs:SDG(1.0)</URN>
            </com:Structure>
        </mes:Structure>
    </mes:Header>
    <mes:DataSet structureRef="SDG">
        <gen:Series>
            <gen:SeriesKey>
                <gen:Value id="REF_AREA" value="1"/>
            </gen:SeriesKey>
            <gen:Obs>
                <gen:ObsDimension value="2008"/>
                <gen:ObsValue value="100"/>
                <gen:Attributes>
                    <gen:Value id="UNIT_MEASURE" value="P"/>
                </gen:Attributes>
            </gen:Obs>
            <gen:Obs>
                <gen:ObsDimension value="2009"/>
                <gen:ObsValue value="150"/>
                <gen:Attributes>
                    <gen:Value id="UNIT_MEASURE" value="P"/>
                </gen:Attributes>
            </gen:Obs>
        </gen:Series>
    </mes:DataSet>
</mes:GenericData>
```

One bit that I'm not 100% clear on is the ObsDimension. In other systems I've seen output where the ObsDimension has an id property, like `<gen:ObsDimension id="TIME_PERIOD" value="2009"/>`. but I'm not sure how to get that id in here. (I'm not sure it's even necessary, to be honest, but would still like to understand it better.)

**Comment by khaeru** [comment]
@brockfanning great, thanks for sharing!

Per `<gen:ObsDimension id="...">`, look at the SDMX-ML standard ("Section 3A" at https://sdmx.org/?page_id=5008), and particularly the document SDMX_2-1_SECTION_3A_PART_IV_DATA.doc at page 9. The text reads (emphasis added):

> ObsDimension holds the key for the grouped observation, i.e. the value of the observation dimension. Note that in this element, **the reference to the dimension is optional**, since it can be inferred from the structure specification for the data set. This saves having to repeat the value unnecessarily. It is assumed that any application processing the data set will have the information from the structure specification available, so that if a dimension identifier is not supplied here, the proper reference can be applied.

In the headers of a lot of the data message specimens we see things like the following; note the `dimensionAtObservation` XML attribute:
https://github.com/khaeru/sdmx/blob/30d8145022ce4837fa426055b1039ec8b9910895/sdmx/tests/data/ECB_EXR/1/M.USD.EUR.SP00.A.xml#L7-L11

There is a corresponding Python attribute [`DataMessage.observation_dimension`](https://sdmx1.readthedocs.io/en/latest/api.html#sdmx.message.DataMessage.observation_dimension). I suspect if you set this (your current code does not), then it will be written out correctly by existing code in `writer.xml`:
https://github.com/khaeru/sdmx/blob/30d8145022ce4837fa426055b1039ec8b9910895/sdmx/writer/xml.py#L122-L123

Note that this will *not* set the `id="…"` XML attribute for every single `<gen:ObsDimension>` element; but it *will* set the message-wide `<mes:Structure dimensionAtObservation="…">` attribute. With this, the message is unambiguous, and any compliant reader should understand the dimension to which `<gen:ObsDimension>` occurs.

Again, please report if this works or not.

**Comment by brockfanning** [comment]
@khaeru Yes, this works great. I'm now using something like this:

```
time_period = next(dim for dim in dsd.dimensions if dim.id == 'TIME_PERIOD')
msg = DataMessage(data=[dataset], dataflow=dfd, header=header, observation_dimension=time_period)     
```

And I'm seeing this in the output:

```
<mes:Structure structureID="SDG" dimensionAtObservation="TIME_PERIOD">
    <com:Structure>
        <URN>urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=IAEG-SDGs:SDG(1.0)</URN>
    </com:Structure>
</mes:Structure>
```

Thanks for the support! I'm happy for this issue to be closed, unless you prefer otherwise.

**Comment by khaeru** [comment]
Good to hear!

I'll close the issue, but note here some enhancements suggested by this discussion. These can be copied to (a) new issue(s) or PR(s):

1. The code should refuse to write an ambiguous message, i.e. most that contain neither `<mes:Structure dimensionAtObservation="...">` or `<gen:ObsDimension id="...">` attributes.

   Note the example above is actually not *logically* ambiguous, since there are only 2 dimensions (REF_AREA and TIME_PERIOD), and 1 is used in the SeriesKey, leaving only 1 that could be referred to by the `<gen:ObsDimension>`. But I am not sure if this is strictly compliant with the standard; and to implement this properly, someone should check.
2. We should clarify in the documentation: even if a specific class like `GenericTimeSeriesDataSet` is used, the `sdmx` code can *not* automatically infer which dimension is the time series/observation dimension.

   This is because the name "TIME_PERIOD" is just one that is commonly used; it is not part of the standard. It's totally possible to have valid structure/data where the dimension has a name like "YEAR". `sdmx` should not use an ad-hoc list to guess. 
3. `to_xml()` could be enhanced, using code like the example above, and adding arguments like `series_dims=` and `obs_dim=` that allow to control precisely how the data are written.
