### ISSUE TITLE
Order of written XML elements in header

### ISSUE THREAD

**Issue by brockfanning** [khaeru/sdmx#42]
We are getting some validation errors on XML output which seem to be about the order of the elements in the header. I suspect this is the fault of the validator we're using, but thought I would ask. I would not have expected that the order of XML elements was important.

Specifically, our validator apparently expects the first element to be "mes:ID". But [here](https://github.com/khaeru/sdmx/blob/master/sdmx/writer/xml.py#L174-L176) the "mes:Test" is written as the first element.

Here's one validation error that we're seeing:

```
Error While Processing XML : Expected element 'ID@http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message' instead of 'Test@http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message' here in element Header@http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message
```

I skimmed through SDMX_2-1_SECTION_3A_PART_I_MESSAGE.doc and did not see any reason to believe that the order of those elements is expected to be a certain way. However it does always list "ID" before "Test" in that documentation. I would appreciate some feedback on whether our validator is to blame, or if the order really does matter. If the latter, I would be happy to submit a PR.

**Comment by khaeru** [comment]
Could you please explain what "our validator" is? I think there are some [XML schema](https://en.wikipedia.org/wiki/XML_Schema_(W3C)) (.xsd) files provided by the SDMX consortium; “Section 3B” on the standards page. Is your validator using these?

XSD definitely allows for order-sensitive vs. -insensitive schemas, so it's possible these could contain something that's not reflected in the plain-language spec.

**Comment by brockfanning** [comment]
@khaeru Thanks for the reply. The validator in question is a Java application called [SDMX Converter](https://webgate.ec.europa.eu/fpfis/wikis/display/RMSDE/SDMX+Converter). Another member of my team already has SDMX Converter set up and has confirmed that manually switching the order of the "ID" and "Test" elements does allow the output to pass validation. Personally I am still struggling to get SDMX Converter to work on my computer (some sort of Java version issue I think).

**Comment by khaeru** [comment]
As I see it, three possibilities:
1. The standard fixes the order of these elements.
2. The order is not fixed.
3. The standard itself is inconsistent: (1) in some places and (2) in others.

If (1), then that tool is accurately implementing the standard. In this case, we'd definitely want to adjust this package to do the same.

If (2), then this is a bug in that tool. It is incorrectly rejecting XML that actually does comply with the standard (which in (2) allows these elements to occur in any order). Then we *could* adjust this package in the interest of compatibility, so long as that doesn't make *this* package violate the standard. But the real fix would be removing that non-standard limitation of the other tool.

If (3), someone ought to contact the SDMX standards group and get some clarification.

To determine which is the case, I'd suggest to inspect the source code of the other tool and/or contact its developer. Someone should also look at those XSD schema files I mentioned. If you aren't familiar with XSD, I can do that.

**Comment by brockfanning** [comment]
That all makes sense to me. I'll do some more investigation and report back soon.

**Comment by brockfanning** [comment]
@khaeru Judging from [these](https://github.com/sdmx-twg/sdmx-ml-v2_1/tree/master/schemas) XSD files, it does look like those elements inside the Header are expected to be in a certain order. For example: https://github.com/sdmx-twg/sdmx-ml-v2_1/blob/master/schemas/SDMXMessage.xsd#L1118-L1119

Given that, I assume we're in situation 1 above, so I'll go ahead and a submit a PR in case it's helpful.
