### ISSUE TITLE
Cannot read StatsCan SDMX-ML 2.0 file

### ISSUE THREAD

**Issue by ramesesjd** [khaeru/sdmx#92]
I hope this is the right place to ask.  If not, I apologize:

I am trying to read some Canadian census data from [Statistics Canada](https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/details/download-telecharger/comp/page_dl-tc.cfm?Lang=E) (the XML option for the "Canada, provinces and territories" geograpic level). The xml file is in the SDMX format and there is a structure file provided, but I cannot figure out how to read the data from the xml file.  As best as I can tell from the documentation,  I should use read_sdmx, with the `dsd` set to the structure file
```
import sdmx

datafile = '~/Documents/Python/Generic_98-401-X2016059.xml'
structure = '~/Documents/Python/Structure_98-401-X2016059.xml'

canada = sdmx.read_sdmx(datafile, dsd = structure)
```

However, running this causes the following after displaying part of the data:
```
Traceback (most recent call last):
  File "/home/myusername/.local/lib/python3.10/site-packages/sdmx/reader/xml.py", line 238, in read_message
    raise NotImplementedError(element.tag, event) from None
NotImplementedError: ('{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message}GenericData', 'start')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myusername/.local/lib/python3.10/site-packages/sdmx/reader/__init__.py", line 126, in read_sdmx
    return reader().read_message(obj, **kwargs)
  File "/home/myusername/.local/lib/python3.10/site-packages/sdmx/reader/xml.py", line 259, in read_message
    raise XMLParseError from exc
sdmx.exceptions.XMLParseError: NotImplementedError: ('{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message}GenericData', 'start')
```

I am certain this isn't an issue with the data files as they are read properly in R (using rsdmx).  Furthermore, trying to open data files from eurostat produces the same result,  Lastly, I don't believe that Statistics Canada provides their data in a manner that I can add a source such that I could use `sdmx.add_source`.

I am quite new to Python so I presume the error is completely on my part due to unfamiliarity.  Any help at all is appreciated.

Thanks in advance!

**Comment by khaeru** [comment]
Hi there,

Some (not all; see dr-leo/pandaSDMX#122) data files from StatsCan are in the older SDMX-ML 2.0 format. You can see a clue to this in `schemas/v2_0/` in the error message you pasted:
```
NotImplementedError: ('{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message}GenericData', 'start')
```

The documentation for this package states that it currently supports only SDMX 2.1. It's not currently on the roadmap to go back and add support for 2.0; we'll instead prioritize adding support for 3.0 (#87).

> Furthermore, trying to open data files from eurostat produces the same result, 

Which specific files? We have nightly tests against the EuroStat web service and test specimens from EuroStat that don't cause problems. Are these perhaps older, archived files that are in the v2.0 format?

> Lastly, I don't believe that Statistics Canada provides their data in a manner that I can add a source such that I could use `sdmx.add_source`.

That's correct. Either StatsCan does not run a web service at all, or the web service API is again the older 2.0 version. (As a Canadian myself, it kind of pains me that my national agency is still lagging behind SDMX 2.1, which was standardized 8 (!) years ago. But that doesn't solve your problem…)

I have never used the rsdmx package, but you might want to try [rpy2](https://rpy2.github.io/doc/v3.4.x/html/index.html) to invoke it from Python, or write a short R script to export the file(s) into a format that can be read in Python. Perhaps that R package would even allow you to convert SDMX-ML 2.0 to SDMX-ML 2.1, and then you could read the resulting file using Python `sdmx`.

**Comment by ramesesjd** [comment]
Hello,

Thanks for your rapid and detailed response!  I'll close the issue as it appears to be on StatsCan's side, but I am providing some responses to your points below. 

> Some (not all; see [dr-leo#122](https://github.com/dr-leo/pandaSDMX/pull/122)) data files from StatsCan are in the older SDMX-ML 2.0 format. You can see a clue to this in `schemas/v2_0/` in the error message you pasted:
> 
> ```
> NotImplementedError: ('{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message}GenericData', 'start')
> ```
> 
> The documentation for this package states that it currently supports only SDMX 2.1. It's not currently on the roadmap to go back and add support for 2.0; we'll instead prioritize adding support for 3.0 (#87).

Ah, this makes sense, and I hadn't noticed that v.2.0 was unsupported.


> > Furthermore, trying to open data files from eurostat produces the same result,
> 
> Which specific files? We have nightly tests against the EuroStat web service and test specimens from EuroStat that don't cause problems. Are these perhaps older, archived files that are in the v2.0 format?

I tried a random file from eurostat; specifically it was the file aact_eaa07.sdmx.zip, from:
[https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Faact_eaa07.sdmx.zip](
https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Faact_eaa07.sdmx.zip)


 
> > Lastly, I don't believe that Statistics Canada provides their data in a manner that I can add a source such that I could use `sdmx.add_source`.
> 
> That's correct. Either StatsCan does not run a web service at all, or the web service API is again the older 2.0 version. (As a Canadian myself, it kind of pains me that my national agency is still lagging behind SDMX 2.1, which was standardized 8 (!) years ago. But that doesn't solve your problem…)

Hopefully the 2021 census data will be released in a supported form.  I'm crossing my fingers but not holding my breath.

> 
> I have never used the rsdmx package, but you might want to try [rpy2](https://rpy2.github.io/doc/v3.4.x/html/index.html) to invoke it from Python, or write a short R script to export the file(s) into a format that can be read in Python. Perhaps that R package would even allow you to convert SDMX-ML 2.0 to SDMX-ML 2.1, and then you could read the resulting file using Python `sdmx`.

Thanks for this suggestion.  I may well try this if my fallback of using the CSV files is not easily workable.

Thanks again for your response and work on this library!
