### ISSUE TITLE
Adding Support for OECD-DataStructure

### ISSUE THREAD

**Issue by exandi** [khaeru/sdmx#95]
Hey,
I was searching for a way to receive data from Eurostat OECD and the World Bank. Therefore, I found the SDMX Interface and started with Eurostat, everything was working fine and configured easily. Next was OECD, there I got into some issues, because OECD isn't fulfill serving the SDMX 2.1 standard!? (Hope I got that right)

Inspired of the functionality of EUROSTAT I build the two following functions to create a same like behavior.

```python
def get_oecd_data_struct(request_id:str)->OrderedDict:
    """returns the datastruct of and OECD-request-id

    Struktur: Dict(dimension:Dict(expression:Dict(language:description)))

    Args:
        request_id (str): OECD Request ID

    Returns:
        OrderedDict: description of the datastruct
    """
    data_structure = requests.get(f"https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/{request_id}")
    data_structure.close()
    root_element = ET.fromstring(data_structure.content.decode())
    codelist = OrderedDict()

    # Dimensions
    for child in root_element.findall("./{*}KeyFamilies/{*}KeyFamily/{*}Components/{*}Dimension"):
        dimension_name = child.attrib["conceptRef"]
        codelist_names = OrderedDict()
        # Codelist
        for code in root_element.findall(f"./{{*}}CodeLists/*[@id='{child.attrib['codelist']}']/{{*}}Code"):
            codelist_value = code.attrib["value"]
            codelist_names[codelist_value] = OrderedDict()
            # Names
            for t in code.findall("./"):
                codelist_names[codelist_value][list(t.attrib.values())[0]] = t.text
        codelist[dimension_name] = codelist_names

    return codelist
```

```python
def build_oecd_key(request_id:str, keys_dict:dict) -> str:
    """Retruns a key that could be used within the `key` argument at the sdmx-interface

    Args:
        request_id (str): ID where data should colleced from
        keys_dict (dict): Key:Expression, how should the dataset be selected
            expression could be value or `MutableSequence` like list or array

    Raises:
        KeyError: is raised if the expression or code is not present in the interface

    Returns:
        str: dimensions are seperated with ".". multiple values are sorted and seperated by "+".

    Todo:
        - check if all keys of `keys_dict` are valid and used
    """
    key_list = list()
    codelist = get_oecd_data_struct(request_id=request_id)
    
    for dimension_name, codelist_names in codelist.items():
        if dimension_name in keys_dict.keys():
            elements = keys_dict[dimension_name]
            if isinstance(elements, MutableSequence):
                for element in elements:
                    if element not in codelist_names.keys():
                        raise KeyError(element, "is an invalid Element. Valid for", dimension_name, "are:", str(list(codelist_names.keys())))
                element_key = "+".join(sorted(elements))
            elif elements is None:
                element_key = ""
            else:
                if elements not in codelist_names.keys():
                        raise KeyError(element, "is an invalid Element. Valid for", dimension_name, "are:", str(list(codelist_names.keys())))
                element_key = str(elements)
            
            key_list.append(element_key)
        else:
            logger.info(f"'{dimension_name}' isn't set valid configs are:\n{list(codelist_names.keys())}")
            key_list.append("")

    
    keys_as_string = ".".join(key_list)+"/all"

    return keys_as_string
```

hope this code will help some other pandasdmx users. I don't exactly know how to create a pull request and where to insert this functions to the code.

**Comment by khaeru** [comment]
> Next was OECD, there I got into some issues, because OECD isn't fulfill serving the SDMX 2.1 standard!? (Hope I got that right)

That's roughly correct. Here's the OECD's API documentation page: https://data.oecd.org/api/sdmx-ml-documentation/ —although this doesn't say so very explicitly, this is the (very old) SDMX 2.0 REST API, not the (more recent) 2.1 version.

Because of limited resources, it is not currently on the roadmap for this `sdmx1` project to support SDMX 2.0 (XML format and API). (If able, we will instead prioritize adding support for the recently released 3.0 standard; see #87) Thus I will mark this as `wontfix`, but leave it here for other users to possibly use your code snippets—thanks for sharing them 🙏🏾 

But in case it wasn't clear `sdmx1` already supports SDMX-JSON data queries from OECD, out of the box! https://data.oecd.org/api/sdmx-json-documentation/ is the documentation on the OECD side. Please see if this meets your needs.

**Comment by exandi** [comment]
> Thus I will mark this as `wontfix`,

okay



> but leave it here for other users to possibly use your code snippets—thanks for sharing them 🙏🏾

yeah that was my intention to share the code





> But in case it wasn't clear `sdmx1` already supports SDMX-JSON data queries from OECD, out of the box! https://data.oecd.org/api/sdmx-json-documentation/ is the documentation on the OECD side. Please see if this meets your needs.

Do you mean, that it should be possible to recive data from OECD with the sdmx packge? If yes could you proide or show a little example I didn't manage to get it to work, else then setting the keys parameter to a manuel created string like param1/param2/param3

**Comment by khaeru** [comment]
> Do you mean, that it should be possible to recive data from OECD with the sdmx packge?

Yes.

> If yes could you proide or show a little example I didn't manage to get it to work, else then setting the keys parameter to a manuel created string like param1/param2/param3

For example, the page reads:

> ## Query examples: Filter expression
>
> If there is a dataset with identifier QNA and with four dimensions, Location, Subject, Measure and Frequency, the SDMX-JSON query would look like the following:
>
> http://stats.oecd.org/sdmx-json/data/QNA/AUS+AUT.GDP+B1_GE.CUR+VOBARSA.Q/all?startTime=2009-Q2&endTime=2011-Q4

So:

```py
from sdmx import Client

OECD = Client("OECD")
data_message = OECD.data("QNA", "AUS+AUT.GDP+B1_GE.CUR+VOBARSA.Q")
```
I currently get an SSL error related to an expired or unsafe certificate on the OECD end, but this is the general approach.

**Comment by exandi** [comment]
Thanks for that, but isn't it possible to build the query string via GetDataStructure Method. you will get the dimensions the order and the valid keys. 

If I will get it to work I will share my code here!
